BoxLayout:
    orientation: "vertical"
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Clear"
            on_press: app.clear_all()
            size_hint_x: 0.2
        TextInput:
            id: input
            text: "insert name here"
    BoxLayout:
        orientation: "horizontal"
        Button:
            text: "Greet"
            on_press: app.show_name()
            size_hint_x: 0.2
        Label:
            id: label_1
